<img align="left" src="img/logo-ucm.png" width="25%">
<br/><br/><br/><br/><br/>


# [Doctorado en Ingeniería (DocIng)](http://www.docing.ucm.cl/index.html)

# [Doctorado en Modelamiento Matemático Aplicado (DM<sub>2</sub>A)](http://vrip.ucm.cl/doctorado-en-modelamiento-matematico-aplicado/)


## Computación Científica I: Introducción a Python para la Investigación. 
### Manejo de arreglos y matrices: Biblioteca NumPy.

&nbsp;
### Profesor: Dr. Ruber Hernández García

<div style="overflow: hidden; display: inline-block;">
    <div style="display: inline-block; max-width: 20%; max-height: 20%;">
        <a href="mailto:rhernandez@ucm.cl">
            <img src="img/email.webp" alt="email" height="24px" width="24px">
        </a>
    </div>
    <div style="display: inline-block; max-width: 20%; max-height: 20%;">
        <a href="www.ruberhg.com">
            <img src="img/website-icon.jpeg" alt="website" height="24px" width="24px">
        </a>
    </div>
    <div style="display: inline-block; max-width: 20%; max-height: 20%;">
        <a href="https://orcid.org/0000-0002-9311-1193">
            <img src="img/orcid.png" alt="orcid" height="24px" width="24px">
        </a> 
    </div>
    <div style="display: inline-block; max-width: 20%; max-height: 20%;">
        <a href="https://github.com/ruberhg" rel="nofollow noreferrer">
            <img src="img/github.png" alt="github" height="24px" width="24px">
        </a>
    </div>
</div>



----

## Introducción a NumPy

Hasta ahora hemos visto los tipos de datos más básicos que nos ofrece Python: integer, real, complex, boolean, list, tuple...  Pero nos falta uno de los más usados en la computación científica: los __arrays__.

_En este notebook nos adentraremos en el paquete NumPy: aprenderemos a crear distintos arrays y a operar con ellos_.

## Recordando: ¿Qué es un array? 

Un array es un __bloque de memoria que contiene elementos del mismo tipo__. Básicamente:

* nos _recuerdan_ a los vectores, matrices, tensores...
* podemos almacenar el array con un nombre y acceder a sus __elementos__ mediante sus __índices__.
* ayudan a gestionar de manera eficiente la memoria y a acelerar los cálculos.


---

| Índice     | 0     | 1     | 2     | 3     | ...   | n-1   | n  |
| ---------- | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| Valor      | 2.1   | 3.6   | 7.8   | 1.5   | ...   | 5.4   | 6.3 |

---

__¿Qué solemos guardar en arrays?__

* Vectores y matrices.
* Datos de experimentos:
    - En distintos instantes discretos.
    - En distintos puntos del espacio.
* Resultado de evaluar funciones con los datos anteriores.
* Discretizaciones para usar algoritmos de: integración, derivación, interpolación...
* ... 

## ¿Qué es NumPy?

NumPy es un paquete fundamental para la programación científica que __proporciona un objeto tipo array__ para almacenar datos de forma eficiente y una serie de __funciones__ para operar y manipular esos datos.
Para usar NumPy lo primero que debemos hacer es importarlo:

In [2]:
import numpy as np

#para ver la versión que tenemos instalada:
np.__version__

'1.20.3'

__Para más información recomendamos ver la [Guía de Usuario](https://numpy.org/doc/1.18/user/index.html) y la [Referencia](https://numpy.org/doc/1.18/reference/index.html) en línea de NumPy.__

## Nuestro primer array

¿No decíamos que Python era fácil? Pues __creemos nuestros primeros arrays__:

In [2]:
import numpy as np

In [3]:
# Array de una dimensión
mi_primer_array = np.array([1, 2, 3, 4]) 
mi_primer_array

array([1, 2, 3, 4])

In [4]:
# Podemos usar print
print(mi_primer_array)

[1 2 3 4]


In [5]:
# Comprobar el tipo de mi_primer_array
type(mi_primer_array)

numpy.ndarray

In [6]:
# Comprobar el tipo de datos que contiene
mi_primer_array.dtype

dtype('int64')

### Arreglos 2D: Matrices

Los arrays de una dimensión se crean pasándole una lista como argumento a la función `np.array`. Para crear un array de dos dimensiones le pasaremos una _lista de listas_:

In [7]:
# Array de dos dimensiones: Matriz
mi_segundo_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

Esto sería una buena manera de definirlo, de acuerdo con el [PEP 8 (indentation)](http://legacy.python.org/dev/peps/pep-0008/#indentation):

In [8]:
mi_segundo_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    ]) 
print(mi_segundo_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


----

## Funciones y constantes de NumPy

Hemos dicho que NumPy también incorporá __funciones__. Un ejemplo sencillo:

In [9]:
# Suma
np.sum(mi_primer_array)

10

In [10]:
# Máximo
np.max(mi_primer_array)

4

In [11]:
# Seno
np.sin(mi_segundo_array)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

Y algunas __constantes__ que podemos necesitar:

In [12]:
np.pi, np.e

(3.141592653589793, 2.718281828459045)

----

## Funciones para crear arrays

Ya hemos visto que la función `np.array()` nos permite crear arrays con los valores que nosotros introduzcamos manualmente a través de listas. Más adelante, aprenderemos a leer ficheros y almacenarlos en arrays. Mientras tanto, ¿qué puede hacernos falta?

### Array de ceros

In [13]:
# En una dimensión
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
# En dos dimensiones
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Array "vacío"

In [15]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

<div class="alert alert-info"><strong>Importante:</strong> 
El array vacío se crea en un tiempo algo inferior al array de ceros. Sin embargo, el valor de sus elementos será arbitrario y dependerá del estado de la memoria. Si lo utilizas asegúrate de que luego llenas bien todos sus elementos porque podrías introducir resultados erróneos.
</div>

### Array de unos

In [16]:
np.ones([3, 2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

<div class="alert alert-info"><strong>Nota:</strong> 
Otras funciones muy útiles son `np.zeros_like` y `np.ones_like`. Usa la ayuda para ver lo que hacen si lo necesitas.
</div>

### Array identidad

In [17]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<div class="alert alert-info"><strong>Nota:</strong> 
También puedes probar `np.eye()` y `np.diag()`.
</div>

----

### Rangos

In [18]:
a = np.arange(0, 5)    # un array que vaya de 0 a 5
a

array([0, 1, 2, 3, 4])

<div class="alert alert-warning"><strong>IMPORTANTE:</strong> 
Mira con atención el resultado anterior, ¿hay algo que deberías grabar en tu cabeza para simpre?
<strong><em>El último elemento no es 5 sino 4.</em></strong>
</div>

In [19]:
np.arange(0, 11, 3)    # un array que vaya de 0 a 10, de 3 en 3

array([0, 3, 6, 9])

Si has tenido que usar MATLAB alguna vez, seguro que esto te suena:

In [20]:
np.linspace(0, 10, 21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

En este caso sí que se incluye el último elemento.

<div class="alert alert-info"><strong>Nota:</strong> 
También puedes probar `np.logspace()`
</div>

Con `np.arange()` es posible crear "vectores" cuyos elementos tomen valores consecutivos o equiespaciados, como hemos visto anteriormente. ¿Podemos hacer lo mismo con "matrices"? Pues sí, pero no usando una sola función. Imagina que quieres crear algo como esto:

\begin{pmatrix}
    1 & 2 & 3\\ 
    4 & 5 & 6\\
    7 & 8 & 9\\
    \end{pmatrix}
    
* Comenzaremos por crear un array 1d con los valores $(1,2,3,4,5,6,7,8,9)$ usando `np.arange()`.
* Luego le daremos forma de array 2d. con `np.reshape(array, (dim0, dim1))`.

In [21]:
a = np.arange(1, 10)
M = np.reshape(a, [3, 3])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
# También funciona como método
N = a.reshape([3,3])
N

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

----

## Operaciones sobre arreglos

#### Operaciones elemento a elemento

Ahora que pocas cosas se nos escapan de los arrays, probemos a hacer algunas operaciones. El funcionamiento es el habitual de MATLAB y poco hay que añadir:

In [23]:
#crear un array y sumarle un número
arr = np.arange(11)
arr + 55

array([55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65])

In [24]:
#multiplicarlo por un número
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [25]:
#elevarlo al cuadrado
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [26]:
#calcular una función
np.tanh(arr)

array([0.        , 0.76159416, 0.96402758, 0.99505475, 0.9993293 ,
       0.9999092 , 0.99998771, 0.99999834, 0.99999977, 0.99999997,
       1.        ])

<div class="alert alert-info"><strong>TAREA:</strong> 
Puedes tratar de comparar la diferencia de tiempo entre realizar la operación en bloque, como ahora, y realizarla elemento a elemento, recorriendo el array con un bucle.
</div>

_Si las operaciones involucran dos arrays también se realizan elemento a elemento:_

In [3]:
import numpy as np
#creamos dos arrays
arr1 = np.arange(0, 11)
arr2 = np.arange(20, 35)

In [4]:
#los sumamos
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (11,) (15,) 

In [29]:
#multiplicamos
arr1 * arr2

array([  0,  21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

### Comparaciones de arreglos

In [5]:
# >,<
arr1 > arr2

ValueError: operands could not be broadcast together with shapes (11,) (15,) 

In [31]:
# ==
arr1 == arr2 # ¡ojo! los arrays son de integers, no de floats

array([False, False, False, False, False, False, False, False, False,
       False, False])

## Características de los arrays de NumPy

El objeto tipo array que proporciona NumPy (Python ya dispone de un tipo array que sirve para almacenar elementos de igual tipo pero no proporciona toda la artillería matemática necesaria como para hacer operaciones de manera rápida y eficiente) se caracteriza por las siguientes razones:

* Homogeneidad de tipo
* Tamaño fijo en el momento de la creación
* Eficiencia

### Homogeneidad de tipo:

Comencemos viendo que ocurre con las __listas__:

In [ ]:
import numpy as np

lista = [ 1, 1+2j, True, 'aerodinamica', [1, 2, 3] ]
lista

En el caso de los arrays:

In [ ]:
array = np.array([ 1, 1+2j, True, 'aerodinamica'])
array

__¿Todo bien? Pues no__. Mientras que en la lista cada elemento conserva su tipo, en el array, todos han de tener el mismo y NumPy ha considerado que todos van a ser string.

### Tamaño fijo en el momento de la creación:

__¡Tranquilo!__ los __allocate__ son automáticos...

Igual que en el caso anterior, comencemos con la __lista__:

In [ ]:
print(id(lista))
lista.append('fluidos')
print(lista)
print(id(lista))

In [ ]:
print(id(array))
array = np.append(array, 'fluidos')
print(array)
print(id(array))

Si consultamos la ayuda de la función `np.append` escribiendo en una celda `help(np.append)` podemos leer:

    Returns
    -------
    append : ndarray
        A copy of `arr` with `values` appended to `axis`.  Note that `append` does not occur in-place: a new array is allocated and filled.  If `axis` is None, `out` is a flattened array.

### Eficiencia:

Hasta el momento los arrays han demostrado ser bastante menos flexibles que las listas, luego olvidemos estos últimos 10 minutos y manejemos siempre listas... ¿no? ¡Pues no! Los arrays realizan una gestión de la memoria mucho más eficiente que mejora el rendimiento.

Prestemos atención ahora a la velocidad de ejecución gracias a la _función mágica_ `%%timeit`, que colocada al inicio de una celda nos indicará el tiempo que tarda en ejecutarse. 

In [6]:
lista = list(range(0,100000))
type(lista)

list

In [7]:
%%timeit
sum(lista)

918 µs ± 225 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
array = np.arange(0, 100000)

In [10]:
%%timeit
np.sum(array)

71.7 µs ± 5.03 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Como ves, las mejoras en este caso son de 2 órdenes de magnitud. __NumPy nos ofrece funciones que se ejecutan prácticamente en tiempos de lenguaje compilado (Fortran, C, C++) y optimizado, pero escribiendo mucho menos código y con un nivel de abstracción mayor__. Conociendo una serie de buenas prácticas, podremos competir en velocidad con nuestros códigos en Python. Para casos en los que no sea posible, existen herramientas que nos permiten ejecutar desde Python nuestros códigos en otros lengujes como [f2py](http://docs.scipy.org/doc/numpy-dev/f2py/). Este tema puede resultarte algo avanzado a estas alturas, pero bastante útil; puedes consultar este [artículo de pybonacci](http://pybonacci.org/2013/02/22/integrar-fortran-con-python-usando-f2py/9) si lo necesitas.

---

___Hasta aquí ha sido una breve introducción sobre este importante y poderoso paquete, pero es necesario continuar profundizando en su uso. Para ello, recomendamos ver:___

* Documenatción de NumPy: https://numpy.org/doc/1.18/user/index.html
* Notebooks adicionales sobre NumPy en el directorio `extra`.
* [100 numpy exercises](https://github.com/rougier/numpy-100). Es posible que de momento sólo sepas hacer los primeros, pero tranquilo, pronto sabrás más...
* [SciPy Lectures](http://scipy-lectures.org/intro/numpy/index.html).

_En definitiva:_
* __Ingenieros y científicos $\heartsuit$ arrays.__
* __Ingenieros y científicos necesitan NumPy.__